<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class AddEnvironmentVariableToContext200ApplicationJSON1
{
    /**
     * ID of the context (UUID)
     * 
     * @var string $contextId
     */
	#[\JMS\Serializer\Annotation\SerializedName('context_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $contextId;
    
    /**
     * The date and time the environment variable was created.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * The date and time the environment variable was updated
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
    /**
     * The name of the environment variable
     * 
     * @var string $variable
     */
	#[\JMS\Serializer\Annotation\SerializedName('variable')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $variable;
    
	public function __construct()
	{
		$this->contextId = "";
		$this->createdAt = new \DateTime();
		$this->updatedAt = new \DateTime();
		$this->variable = "";
	}
}
