<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class CancelJobResponse
{
	
    public string $contentType;
    
	
    public ?CancelJobMessageResponse $messageResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\CancelJobDefaultApplicationJSON $cancelJobDefaultApplicationJSONObject
     */
	
    public ?CancelJobDefaultApplicationJSON $cancelJobDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->messageResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->cancelJobDefaultApplicationJSONObject = null;
	}
}
