<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class ContinuePipelineResponse
{
	
    public string $contentType;
    
    /**
     * A confirmation message.
     * 
     * @var ?\CircleCi\Models\Operations\ContinuePipelineMessageResponse $messageResponse
     */
	
    public ?ContinuePipelineMessageResponse $messageResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\ContinuePipelineDefaultApplicationJSON $continuePipelineDefaultApplicationJSONObject
     */
	
    public ?ContinuePipelineDefaultApplicationJSON $continuePipelineDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->messageResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->continuePipelineDefaultApplicationJSONObject = null;
	}
}
