<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** Day in a week, in three letters format */
enum CreateScheduleScheduleTimetable2DaysOfWeekEnum: string
{
    case TUE = 'TUE';
    case SAT = 'SAT';
    case SUN = 'SUN';
    case MON = 'MON';
    case THU = 'THU';
    case WED = 'WED';
    case FRI = 'FRI';
}
