<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** Type of the scope being used */
enum CreateWebhookRequestBodyScopeTypeEnum: string
{
    case PROJECT = 'project';
}
