<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of checkout key to create. This may be either `deploy-key` or `user-key`. */
enum CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputTypeEnum: string
{
    case USER_KEY = 'user-key';
    case DEPLOY_KEY = 'deploy-key';
}
