<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of checkout key. This may be either `deploy-key` or `github-user-key`. */
enum CreateCheckoutKeyCheckoutKeyCheckoutKeyType: string
{
    case DeployKey = 'deploy-key';
    case GithubUserKey = 'github-user-key';
}
