<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class CreateWebhookResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A webhook
     * 
     * @var ?\CircleCi\Models\Operations\CreateWebhookWebhook $webhook
     */
	
    public ?CreateWebhookWebhook $webhook = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\CreateWebhookDefaultApplicationJSON $createWebhookDefaultApplicationJSONObject
     */
	
    public ?CreateWebhookDefaultApplicationJSON $createWebhookDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->webhook = null;
		$this->createWebhookDefaultApplicationJSONObject = null;
	}
}
