<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * CreateScheduleCreateScheduleParameters - The parameters for a create schedule request
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class CreateScheduleCreateScheduleParameters
{
    /**
     * The attribution-actor of the scheduled pipeline.
     * 
     * @var \CircleCi\Models\Operations\CreateScheduleCreateScheduleParametersAttributionActor $attributionActor
     */
	#[\JMS\Serializer\Annotation\SerializedName('attribution-actor')]
    #[\JMS\Serializer\Annotation\Type('enum<CircleCi\Models\Operations\CreateScheduleCreateScheduleParametersAttributionActor>')]
    public CreateScheduleCreateScheduleParametersAttributionActor $attributionActor;
    
    /**
     * Description of the schedule.
     * 
     * @var ?string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
    /**
     * Name of the schedule.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Pipeline parameters represented as key-value pairs. Must contain branch or tag.
     * 
     * @var array<string, mixed> $parameters
     */
	#[\JMS\Serializer\Annotation\SerializedName('parameters')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    public array $parameters;
    
    /**
     * Timetable that specifies when a schedule triggers.
     * 
     * @var mixed $timetable
     */
	#[\JMS\Serializer\Annotation\SerializedName('timetable')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $timetable;
    
	public function __construct()
	{
		$this->attributionActor = \CircleCi\Models\Operations\CreateScheduleCreateScheduleParametersAttributionActor::Current;
		$this->description = null;
		$this->name = "";
		$this->parameters = [];
		$this->timetable = null;
	}
}
