<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class CreateCheckoutKeyResponse
{
    /**
     * The checkout key.
     * 
     * @var ?\CircleCi\Models\Operations\CreateCheckoutKeyCheckoutKey $checkoutKey
     */
	
    public ?CreateCheckoutKeyCheckoutKey $checkoutKey = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\CreateCheckoutKeyDefaultApplicationJSON $createCheckoutKeyDefaultApplicationJSONObject
     */
	
    public ?CreateCheckoutKeyDefaultApplicationJSON $createCheckoutKeyDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->checkoutKey = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->createCheckoutKeyDefaultApplicationJSONObject = null;
	}
}
