<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of owner. Defaults to "organization". Accounts are only used as context owners in server and must be specified by an id instead of a slug. */
enum CreateContextRequestBodyOwner2Type: string
{
    case Organization = 'organization';
}
