<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** Month, in three letters format. */
enum CreateScheduleScheduleTimetable1Months: string
{
    case MAR = 'MAR';
    case NOV = 'NOV';
    case DEC = 'DEC';
    case JUN = 'JUN';
    case MAY = 'MAY';
    case OCT = 'OCT';
    case FEB = 'FEB';
    case APR = 'APR';
    case SEP = 'SEP';
    case AUG = 'AUG';
    case JAN = 'JAN';
    case JUL = 'JUL';
}
