<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class CreateContextRequestBodyOwner2
{
    /**
     * A string that represents an organization. Specify either this or id. Cannot be used for accounts.
     * 
     * @var string $slug
     */
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
    /**
     * The type of owner. Defaults to "organization". Accounts are only used as context owners in server and must be specified by an id instead of a slug.
     * 
     * @var ?\CircleCi\Models\Operations\CreateContextRequestBodyOwner2Type $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<CircleCi\Models\Operations\CreateContextRequestBodyOwner2Type>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateContextRequestBodyOwner2Type $type = null;
    
	public function __construct()
	{
		$this->slug = "";
		$this->type = null;
	}
}
