<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of the owner. Defaults to "organization". Accounts are only used as context owners in server. */
enum CreateContextRequestBodyOwner1TypeEnum: string
{
    case ACCOUNT = 'account';
    case ORGANIZATION = 'organization';
}
