<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The attribution-actor of the scheduled pipeline. */
enum CreateScheduleCreateScheduleParametersAttributionActorEnum: string
{
    case CURRENT = 'current';
    case SYSTEM = 'system';
}
