<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class DeleteWebhookResponse
{
	
    public string $contentType;
    
    /**
     * A confirmation message
     * 
     * @var ?\CircleCi\Models\Operations\DeleteWebhookMessageResponse $messageResponse
     */
	
    public ?DeleteWebhookMessageResponse $messageResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\DeleteWebhookDefaultApplicationJSON $deleteWebhookDefaultApplicationJSONObject
     */
	
    public ?DeleteWebhookDefaultApplicationJSON $deleteWebhookDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->messageResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->deleteWebhookDefaultApplicationJSONObject = null;
	}
}
