<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * DeleteContextMessageResponse - message response
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class DeleteContextMessageResponse
{
    /**
     * A human-readable message
     * 
     * @var string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	public function __construct()
	{
		$this->message = "";
	}
}
