<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class DeleteScheduleByIdRequest
{
    /**
     * The unique ID of the schedule.
     * 
     * @var string $scheduleId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=schedule-id')]
    public string $scheduleId;
    
	public function __construct()
	{
		$this->scheduleId = "";
	}
}
