<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class GetAllInsightsBranchesRequest
{
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     * 
     * @var string $projectSlug
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project-slug')]
    public string $projectSlug;
    
    /**
     * The name of a workflow. If not passed we will scope the API call to the project.
     * 
     * @var ?string $workflowName
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=workflow-name')]
    public ?string $workflowName = null;
    
	public function __construct()
	{
		$this->projectSlug = "";
		$this->workflowName = null;
	}
}
