<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetAllInsightsBranchesResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A list of branches for a project
     * 
     * @var mixed $getAllInsightsBranches200ApplicationJSONAny
     */
	
    public mixed $getAllInsightsBranches200ApplicationJSONAny = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetAllInsightsBranchesDefaultApplicationJSON $getAllInsightsBranchesDefaultApplicationJSONObject
     */
	
    public ?GetAllInsightsBranchesDefaultApplicationJSON $getAllInsightsBranchesDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getAllInsightsBranches200ApplicationJSONAny = null;
		$this->getAllInsightsBranchesDefaultApplicationJSONObject = null;
	}
}
