<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetCollaborationsCollaboration
{
    /**
     * URL to the user's avatar on the VCS
     * 
     * @var string $avatarUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('avatar_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $avatarUrl;
    
    /**
     * The UUID of the organization
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The name of the organization
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The slug of the organization
     * 
     * @var string $slug
     */
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
    /**
     * The VCS provider
     * 
     * @var string $vcsType
     */
	#[\JMS\Serializer\Annotation\SerializedName('vcs-type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $vcsType;
    
	public function __construct()
	{
		$this->avatarUrl = "";
		$this->id = "";
		$this->name = "";
		$this->slug = "";
		$this->vcsType = "";
	}
}
