<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetCollaborationsResponse
{
    /**
     * Collaborations
     * 
     * @var ?array<\CircleCi\Models\Operations\GetCollaborationsCollaboration> $collaborations
     */
	
    public ?array $collaborations = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetCollaborationsDefaultApplicationJSON $getCollaborationsDefaultApplicationJSONObject
     */
	
    public ?GetCollaborationsDefaultApplicationJSON $getCollaborationsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->collaborations = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getCollaborationsDefaultApplicationJSONObject = null;
	}
}
