<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetCheckoutKeyResponse
{
    /**
     * The checkout key.
     * 
     * @var ?\CircleCi\Models\Operations\GetCheckoutKeyCheckoutKey $checkoutKey
     */
	
    public ?GetCheckoutKeyCheckoutKey $checkoutKey = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetCheckoutKeyDefaultApplicationJSON $getCheckoutKeyDefaultApplicationJSONObject
     */
	
    public ?GetCheckoutKeyDefaultApplicationJSON $getCheckoutKeyDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->checkoutKey = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getCheckoutKeyDefaultApplicationJSONObject = null;
	}
}
