<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetCurrentUserResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * User login information.
     * 
     * @var ?\CircleCi\Models\Operations\GetCurrentUserUser $user
     */
	
    public ?GetCurrentUserUser $user = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetCurrentUserDefaultApplicationJSON $getCurrentUserDefaultApplicationJSONObject
     */
	
    public ?GetCurrentUserDefaultApplicationJSON $getCurrentUserDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->user = null;
		$this->getCurrentUserDefaultApplicationJSONObject = null;
	}
}
