<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of checkout key. This may be either `deploy-key` or `github-user-key`. */
enum GetCheckoutKeyCheckoutKeyCheckoutKeyTypeEnum: string
{
    case DEPLOY_KEY = 'deploy-key';
    case GITHUB_USER_KEY = 'github-user-key';
}
