<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetFlakyTests200ApplicationJSON - Flaky tests response
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetFlakyTests200ApplicationJSON
{
    /**
     * A list of all instances of flakes. Note that a test is no longer considered flaky after 2 weeks have passed without a flake. Each flake resets this timer.
     * 
     * @var array<\CircleCi\Models\Operations\GetFlakyTests200ApplicationJSONFlakyTests> $flakyTests
     */
	#[\JMS\Serializer\Annotation\SerializedName('flaky-tests')]
    #[\JMS\Serializer\Annotation\Type('array<CircleCi\Models\Operations\GetFlakyTests200ApplicationJSONFlakyTests>')]
    public array $flakyTests;
    
    /**
     * A count of unique tests that have failed. If your project has N tests that have flaked multiple times each, this will be equal to N.
     * 
     * @var float $totalFlakyTests
     */
	#[\JMS\Serializer\Annotation\SerializedName('total-flaky-tests')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $totalFlakyTests;
    
	public function __construct()
	{
		$this->flakyTests = [];
		$this->totalFlakyTests = 0;
	}
}
