<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetFlakyTests200ApplicationJSONFlakyTests
{
    /**
     * The class the test belongs to.
     * 
     * @var string $classname
     */
	#[\JMS\Serializer\Annotation\SerializedName('classname')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $classname;
    
    /**
     * The file the test belongs to.
     * 
     * @var string $file
     */
	#[\JMS\Serializer\Annotation\SerializedName('file')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $file;
    
    /**
     * The name of the job.
     * 
     * @var string $jobName
     */
	#[\JMS\Serializer\Annotation\SerializedName('job-name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $jobName;
    
    /**
     * The number of the job.
     * 
     * @var int $jobNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('job-number')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $jobNumber;
    
    /**
     * The number of the pipeline.
     * 
     * @var int $pipelineNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('pipeline-number')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $pipelineNumber;
    
    /**
     * The source of the test.
     * 
     * @var string $source
     */
	#[\JMS\Serializer\Annotation\SerializedName('source')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $source;
    
    /**
     * The name of the test.
     * 
     * @var string $testName
     */
	#[\JMS\Serializer\Annotation\SerializedName('test-name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $testName;
    
	#[\JMS\Serializer\Annotation\SerializedName('time-wasted')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $timeWasted = null;
    
    /**
     * The number of times the test flaked.
     * 
     * @var int $timesFlaked
     */
	#[\JMS\Serializer\Annotation\SerializedName('times-flaked')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $timesFlaked;
    
    /**
     * The date and time when workflow was created.
     * 
     * @var mixed $workflowCreatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow-created-at')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $workflowCreatedAt;
    
    /**
     * The ID of the workflow associated with the provided test counts
     * 
     * @var mixed $workflowId
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow-id')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $workflowId;
    
    /**
     * The name of the workflow.
     * 
     * @var string $workflowName
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow-name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workflowName;
    
	public function __construct()
	{
		$this->classname = "";
		$this->file = "";
		$this->jobName = "";
		$this->jobNumber = 0;
		$this->pipelineNumber = 0;
		$this->source = "";
		$this->testName = "";
		$this->timeWasted = null;
		$this->timesFlaked = 0;
		$this->workflowCreatedAt = null;
		$this->workflowId = null;
		$this->workflowName = "";
	}
}
