<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetFlakyTestsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A list of flaky tests for a project
     * 
     * @var ?\CircleCi\Models\Operations\GetFlakyTests200ApplicationJSON $getFlakyTests200ApplicationJSONObject
     */
	
    public ?GetFlakyTests200ApplicationJSON $getFlakyTests200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetFlakyTestsDefaultApplicationJSON $getFlakyTestsDefaultApplicationJSONObject
     */
	
    public ?GetFlakyTestsDefaultApplicationJSON $getFlakyTestsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getFlakyTests200ApplicationJSONObject = null;
		$this->getFlakyTestsDefaultApplicationJSONObject = null;
	}
}
