<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetJobTimeseries200ApplicationJSONItems
{
    /**
     * The end time of the last execution included in the metrics.
     * 
     * @var \DateTime $maxEndedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('max_ended_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $maxEndedAt;
    
    /**
     * Metrics relating to a workflow's runs.
     * 
     * @var \CircleCi\Models\Operations\GetJobTimeseries200ApplicationJSONItemsMetrics $metrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetJobTimeseries200ApplicationJSONItemsMetrics')]
    public GetJobTimeseries200ApplicationJSONItemsMetrics $metrics;
    
    /**
     * The start time for the earliest execution included in the metrics.
     * 
     * @var \DateTime $minStartedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('min_started_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $minStartedAt;
    
    /**
     * The name of the workflow.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The start of the interval for timeseries metrics.
     * 
     * @var \DateTime $timestamp
     */
	#[\JMS\Serializer\Annotation\SerializedName('timestamp')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $timestamp;
    
	public function __construct()
	{
		$this->maxEndedAt = new \DateTime();
		$this->metrics = new \CircleCi\Models\Operations\GetJobTimeseries200ApplicationJSONItemsMetrics();
		$this->minStartedAt = new \DateTime();
		$this->name = "";
		$this->timestamp = new \DateTime();
	}
}
