<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetJobDetailsResponse
{
	
    public string $contentType;
    
    /**
     * Job details.
     * 
     * @var ?\CircleCi\Models\Operations\GetJobDetailsJobDetails $jobDetails
     */
	
    public ?GetJobDetailsJobDetails $jobDetails = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetJobDetailsDefaultApplicationJSON $getJobDetailsDefaultApplicationJSONObject
     */
	
    public ?GetJobDetailsDefaultApplicationJSON $getJobDetailsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->jobDetails = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getJobDetailsDefaultApplicationJSONObject = null;
	}
}
