<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetJobDetailsJobDetailsProject - Information about a project.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetJobDetailsJobDetailsProject
{
    /**
     * URL to the repository hosting the project's code
     * 
     * @var string $externalUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('external_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $externalUrl;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The name of the project
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     * 
     * @var string $slug
     */
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
	public function __construct()
	{
		$this->externalUrl = "";
		$this->id = "";
		$this->name = "";
		$this->slug = "";
	}
}
