<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetJobDetailsJobDetailsParallelRuns - Info about a status of the parallel run.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetJobDetailsJobDetailsParallelRuns
{
    /**
     * Index of the parallel run.
     * 
     * @var int $index
     */
	#[\JMS\Serializer\Annotation\SerializedName('index')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $index;
    
    /**
     * Status of the parallel run.
     * 
     * @var string $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
	public function __construct()
	{
		$this->index = 0;
		$this->status = "";
	}
}
