<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetJobTimeseries200ApplicationJSONItemsMetrics - Metrics relating to a workflow's runs.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetJobTimeseries200ApplicationJSONItemsMetrics
{
    /**
     * Metrics relating to the duration of runs for a workflow.
     * 
     * @var \CircleCi\Models\Operations\GetJobTimeseries200ApplicationJSONItemsMetricsDurationMetrics $durationMetrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('duration_metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetJobTimeseries200ApplicationJSONItemsMetricsDurationMetrics')]
    public GetJobTimeseries200ApplicationJSONItemsMetricsDurationMetrics $durationMetrics;
    
    /**
     * The number of failed runs.
     * 
     * @var int $failedRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('failed_runs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $failedRuns;
    
    /**
     * The median credits consumed over the current timeseries interval.
     * 
     * @var int $medianCreditsUsed
     */
	#[\JMS\Serializer\Annotation\SerializedName('median_credits_used')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $medianCreditsUsed;
    
    /**
     * The number of successful runs.
     * 
     * @var int $successfulRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('successful_runs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $successfulRuns;
    
    /**
     * The average number of runs per day.
     * 
     * @var float $throughput
     */
	#[\JMS\Serializer\Annotation\SerializedName('throughput')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $throughput;
    
    /**
     * The total credits consumed over the current timeseries interval.
     * 
     * @var int $totalCreditsUsed
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_credits_used')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalCreditsUsed;
    
    /**
     * The total number of runs.
     * 
     * @var int $totalRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_runs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalRuns;
    
	public function __construct()
	{
		$this->durationMetrics = new \CircleCi\Models\Operations\GetJobTimeseries200ApplicationJSONItemsMetricsDurationMetrics();
		$this->failedRuns = 0;
		$this->medianCreditsUsed = 0;
		$this->successfulRuns = 0;
		$this->throughput = 0;
		$this->totalCreditsUsed = 0;
		$this->totalRuns = 0;
	}
}
