<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class GetJobTimeseriesRequest
{
    /**
     * The name of a vcs branch. If not passed we will scope the API call to the default branch.
     * 
     * @var ?string $branch
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=branch')]
    public ?string $branch = null;
    
    /**
     * Include only executions that started before this date. This date can be at most 90 days after the start-date.
     * 
     * @var ?\DateTime $endDate
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end-date,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $endDate = null;
    
    /**
     * The granularity for which to query timeseries data.
     * 
     * @var ?\CircleCi\Models\Operations\GetJobTimeseriesGranularity $granularity
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=granularity')]
    public ?GetJobTimeseriesGranularity $granularity = null;
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     * 
     * @var string $projectSlug
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project-slug')]
    public string $projectSlug;
    
    /**
     * Include only executions that started at or after this date. This must be specified if an end-date is provided.
     * 
     * @var ?\DateTime $startDate
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start-date,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $startDate = null;
    
    /**
     * The name of the workflow.
     * 
     * @var string $workflowName
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workflow-name')]
    public string $workflowName;
    
	public function __construct()
	{
		$this->branch = null;
		$this->endDate = null;
		$this->granularity = null;
		$this->projectSlug = "";
		$this->startDate = null;
		$this->workflowName = "";
	}
}
