<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetJobTimeseriesResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * An array of timeseries data, one entry per job.
     * 
     * @var ?\CircleCi\Models\Operations\GetJobTimeseries200ApplicationJSON $getJobTimeseries200ApplicationJSONObject
     */
	
    public ?GetJobTimeseries200ApplicationJSON $getJobTimeseries200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetJobTimeseriesDefaultApplicationJSON $getJobTimeseriesDefaultApplicationJSONObject
     */
	
    public ?GetJobTimeseriesDefaultApplicationJSON $getJobTimeseriesDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getJobTimeseries200ApplicationJSONObject = null;
		$this->getJobTimeseriesDefaultApplicationJSONObject = null;
	}
}
