<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The current status of the job. */
enum GetJobDetailsJobDetailsStatusEnum: string
{
    case SUCCESS = 'success';
    case RUNNING = 'running';
    case NOT_RUN = 'not_run';
    case FAILED = 'failed';
    case RETRIED = 'retried';
    case QUEUED = 'queued';
    case NOT_RUNNING = 'not_running';
    case INFRASTRUCTURE_FAIL = 'infrastructure_fail';
    case TIMEDOUT = 'timedout';
    case ON_HOLD = 'on_hold';
    case TERMINATED_UNKNOWN = 'terminated-unknown';
    case BLOCKED = 'blocked';
    case CANCELED = 'canceled';
    case UNAUTHORIZED = 'unauthorized';
}
