<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetJobArtifactsArtifactListResponseArtifact - An artifact
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetJobArtifactsArtifactListResponseArtifact
{
    /**
     * The index of the node that stored the artifact.
     * 
     * @var int $nodeIndex
     */
	#[\JMS\Serializer\Annotation\SerializedName('node_index')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $nodeIndex;
    
    /**
     * The artifact path.
     * 
     * @var string $path
     */
	#[\JMS\Serializer\Annotation\SerializedName('path')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $path;
    
    /**
     * The URL to download the artifact contents.
     * 
     * @var string $url
     */
	#[\JMS\Serializer\Annotation\SerializedName('url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $url;
    
	public function __construct()
	{
		$this->nodeIndex = 0;
		$this->path = "";
		$this->url = "";
	}
}
