<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetJobDetailsJobDetails - Job Details
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetJobDetailsJobDetails
{
    /**
     * List of contexts used by the job.
     * 
     * @var array<\CircleCi\Models\Operations\GetJobDetailsJobDetailsContexts> $contexts
     */
	#[\JMS\Serializer\Annotation\SerializedName('contexts')]
    #[\JMS\Serializer\Annotation\Type('array<CircleCi\Models\Operations\GetJobDetailsJobDetailsContexts>')]
    public array $contexts;
    
    /**
     * The time when the job was created.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * Duration of a job in milliseconds.
     * 
     * @var int $duration
     */
	#[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $duration;
    
    /**
     * Information about executor used for a job.
     * 
     * @var \CircleCi\Models\Operations\GetJobDetailsJobDetailsExecutor $executor
     */
	#[\JMS\Serializer\Annotation\SerializedName('executor')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetJobDetailsJobDetailsExecutor')]
    public GetJobDetailsJobDetailsExecutor $executor;
    
    /**
     * Info about the latest workflow the job was a part of.
     * 
     * @var \CircleCi\Models\Operations\GetJobDetailsJobDetailsLatestWorkflow $latestWorkflow
     */
	#[\JMS\Serializer\Annotation\SerializedName('latest_workflow')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetJobDetailsJobDetailsLatestWorkflow')]
    public GetJobDetailsJobDetailsLatestWorkflow $latestWorkflow;
    
    /**
     * Messages from CircleCI execution platform.
     * 
     * @var array<\CircleCi\Models\Operations\GetJobDetailsJobDetailsMessages> $messages
     */
	#[\JMS\Serializer\Annotation\SerializedName('messages')]
    #[\JMS\Serializer\Annotation\Type('array<CircleCi\Models\Operations\GetJobDetailsJobDetailsMessages>')]
    public array $messages;
    
    /**
     * The name of the job.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The number of the job.
     * 
     * @var int $number
     */
	#[\JMS\Serializer\Annotation\SerializedName('number')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $number;
    
    /**
     * Information about an organization.
     * 
     * @var \CircleCi\Models\Operations\GetJobDetailsJobDetailsOrganization $organization
     */
	#[\JMS\Serializer\Annotation\SerializedName('organization')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetJobDetailsJobDetailsOrganization')]
    public GetJobDetailsJobDetailsOrganization $organization;
    
    /**
     * Info about parallels runs and their status.
     * 
     * @var array<\CircleCi\Models\Operations\GetJobDetailsJobDetailsParallelRuns> $parallelRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('parallel_runs')]
    #[\JMS\Serializer\Annotation\Type('array<CircleCi\Models\Operations\GetJobDetailsJobDetailsParallelRuns>')]
    public array $parallelRuns;
    
    /**
     * A number of parallel runs the job has.
     * 
     * @var int $parallelism
     */
	#[\JMS\Serializer\Annotation\SerializedName('parallelism')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $parallelism;
    
    /**
     * Info about a pipeline the job is a part of.
     * 
     * @var \CircleCi\Models\Operations\GetJobDetailsJobDetailsPipeline $pipeline
     */
	#[\JMS\Serializer\Annotation\SerializedName('pipeline')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetJobDetailsJobDetailsPipeline')]
    public GetJobDetailsJobDetailsPipeline $pipeline;
    
    /**
     * Information about a project.
     * 
     * @var \CircleCi\Models\Operations\GetJobDetailsJobDetailsProject $project
     */
	#[\JMS\Serializer\Annotation\SerializedName('project')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetJobDetailsJobDetailsProject')]
    public GetJobDetailsJobDetailsProject $project;
    
    /**
     * The time when the job was placed in a queue.
     * 
     * @var \DateTime $queuedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('queued_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $queuedAt;
    
    /**
     * The date and time the job started.
     * 
     * @var \DateTime $startedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('started_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $startedAt;
    
    /**
     * The current status of the job.
     * 
     * @var \CircleCi\Models\Operations\GetJobDetailsJobDetailsStatusEnum $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<CircleCi\Models\Operations\GetJobDetailsJobDetailsStatusEnum>')]
    public GetJobDetailsJobDetailsStatusEnum $status;
    
    /**
     * The time when the job stopped.
     * 
     * @var ?\DateTime $stoppedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('stopped_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $stoppedAt = null;
    
    /**
     * URL of the job in CircleCI Web UI.
     * 
     * @var string $webUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('web_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $webUrl;
    
	public function __construct()
	{
		$this->contexts = [];
		$this->createdAt = new \DateTime();
		$this->duration = 0;
		$this->executor = new \CircleCi\Models\Operations\GetJobDetailsJobDetailsExecutor();
		$this->latestWorkflow = new \CircleCi\Models\Operations\GetJobDetailsJobDetailsLatestWorkflow();
		$this->messages = [];
		$this->name = "";
		$this->number = 0;
		$this->organization = new \CircleCi\Models\Operations\GetJobDetailsJobDetailsOrganization();
		$this->parallelRuns = [];
		$this->parallelism = 0;
		$this->pipeline = new \CircleCi\Models\Operations\GetJobDetailsJobDetailsPipeline();
		$this->project = new \CircleCi\Models\Operations\GetJobDetailsJobDetailsProject();
		$this->queuedAt = new \DateTime();
		$this->startedAt = new \DateTime();
		$this->status = \CircleCi\Models\Operations\GetJobDetailsJobDetailsStatusEnum::SUCCESS;
		$this->stoppedAt = null;
		$this->webUrl = "";
	}
}
