<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetJobArtifactsResponse
{
    /**
     * A paginated list of the job's artifacts.
     * 
     * @var ?\CircleCi\Models\Operations\GetJobArtifactsArtifactListResponse $artifactListResponse
     */
	
    public ?GetJobArtifactsArtifactListResponse $artifactListResponse = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetJobArtifactsDefaultApplicationJSON $getJobArtifactsDefaultApplicationJSONObject
     */
	
    public ?GetJobArtifactsDefaultApplicationJSON $getJobArtifactsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->artifactListResponse = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getJobArtifactsDefaultApplicationJSONObject = null;
	}
}
