<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetOrgSummaryDataProjectNames - List of project names.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetOrgSummaryDataProjectNames
{
	public function __construct()
	{
	}
}
