<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetOrgSummaryData200ApplicationJSONOrgProjectDataTrends - Trends for a single project, across all branches.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetOrgSummaryData200ApplicationJSONOrgProjectDataTrends
{
    /**
     * The trend value for the success rate.
     * 
     * @var float $successRate
     */
	#[\JMS\Serializer\Annotation\SerializedName('success_rate')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $successRate;
    
    /**
     * The trend value for total credits consumed.
     * 
     * @var float $totalCreditsUsed
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_credits_used')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $totalCreditsUsed;
    
    /**
     * Trend value for total duration.
     * 
     * @var float $totalDurationSecs
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_duration_secs')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $totalDurationSecs;
    
    /**
     * The trend value for total number of runs.
     * 
     * @var float $totalRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_runs')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $totalRuns;
    
	public function __construct()
	{
		$this->successRate = 0;
		$this->totalCreditsUsed = 0;
		$this->totalDurationSecs = 0;
		$this->totalRuns = 0;
	}
}
