<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetOrgSummaryDataResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * summary metrics with trends for an entire org and it's projects.
     * 
     * @var ?\CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSON $getOrgSummaryData200ApplicationJSONObject
     */
	
    public ?GetOrgSummaryData200ApplicationJSON $getOrgSummaryData200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetOrgSummaryDataDefaultApplicationJSON $getOrgSummaryDataDefaultApplicationJSONObject
     */
	
    public ?GetOrgSummaryDataDefaultApplicationJSON $getOrgSummaryDataDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getOrgSummaryData200ApplicationJSONObject = null;
		$this->getOrgSummaryDataDefaultApplicationJSONObject = null;
	}
}
