<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetOrgSummaryData200ApplicationJSONOrgData - Aggregated metrics for an org, with trends.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetOrgSummaryData200ApplicationJSONOrgData
{
    /**
     * Metrics for a single org metrics.
     * 
     * @var \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgDataMetrics $metrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgDataMetrics')]
    public GetOrgSummaryData200ApplicationJSONOrgDataMetrics $metrics;
    
    /**
     * Trends for a single org.
     * 
     * @var \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgDataTrends $trends
     */
	#[\JMS\Serializer\Annotation\SerializedName('trends')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgDataTrends')]
    public GetOrgSummaryData200ApplicationJSONOrgDataTrends $trends;
    
	public function __construct()
	{
		$this->metrics = new \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgDataMetrics();
		$this->trends = new \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgDataTrends();
	}
}
