<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetOrgSummaryData200ApplicationJSON - Summary metrics with trends for the entire org, and for each project.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetOrgSummaryData200ApplicationJSON
{
    /**
     * A list of all the project names in the organization.
     * 
     * @var array<string> $allProjects
     */
	#[\JMS\Serializer\Annotation\SerializedName('all_projects')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $allProjects;
    
    /**
     * Aggregated metrics for an org, with trends.
     * 
     * @var \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgData $orgData
     */
	#[\JMS\Serializer\Annotation\SerializedName('org_data')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgData')]
    public GetOrgSummaryData200ApplicationJSONOrgData $orgData;
    
    /**
     * Metrics for a single project, across all branches
     * 
     * @var array<\CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgProjectData> $orgProjectData
     */
	#[\JMS\Serializer\Annotation\SerializedName('org_project_data')]
    #[\JMS\Serializer\Annotation\Type('array<CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgProjectData>')]
    public array $orgProjectData;
    
	public function __construct()
	{
		$this->allProjects = [];
		$this->orgData = new \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgData();
		$this->orgProjectData = [];
	}
}
