<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetOrgSummaryData200ApplicationJSONOrgProjectData
{
    /**
     * Metrics for a single project, across all branches.
     * 
     * @var \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgProjectDataMetrics $metrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgProjectDataMetrics')]
    public GetOrgSummaryData200ApplicationJSONOrgProjectDataMetrics $metrics;
    
    /**
     * The name of the project.
     * 
     * @var string $projectName
     */
	#[\JMS\Serializer\Annotation\SerializedName('project_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $projectName;
    
    /**
     * Trends for a single project, across all branches.
     * 
     * @var \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgProjectDataTrends $trends
     */
	#[\JMS\Serializer\Annotation\SerializedName('trends')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgProjectDataTrends')]
    public GetOrgSummaryData200ApplicationJSONOrgProjectDataTrends $trends;
    
	public function __construct()
	{
		$this->metrics = new \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgProjectDataMetrics();
		$this->projectName = "";
		$this->trends = new \CircleCi\Models\Operations\GetOrgSummaryData200ApplicationJSONOrgProjectDataTrends();
	}
}
