<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** Workflow status. */
enum GetProjectWorkflowRuns200ApplicationJSONItemsStatus: string
{
    case Success = 'success';
    case Failed = 'failed';
    case Error = 'error';
    case Canceled = 'canceled';
    case Unauthorized = 'unauthorized';
}
