<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetPipelineConfigByIdPipelineConfig - The configuration strings for the pipeline.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetPipelineConfigByIdPipelineConfig
{
    /**
     * The compiled configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline's configuration, then this field may be empty.
     * 
     * @var string $compiled
     */
	#[\JMS\Serializer\Annotation\SerializedName('compiled')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $compiled;
    
    /**
     * The compiled setup configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline's setup workflows, then this field may be empty.
     * 
     * @var ?string $compiledSetupConfig
     */
	#[\JMS\Serializer\Annotation\SerializedName('compiled-setup-config')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $compiledSetupConfig = null;
    
    /**
     * The setup configuration for the pipeline used for Setup Workflows. If there were errors processing the pipeline's configuration or if setup workflows are not enabled, then this field should not exist
     * 
     * @var ?string $setupConfig
     */
	#[\JMS\Serializer\Annotation\SerializedName('setup-config')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $setupConfig = null;
    
    /**
     * The source configuration for the pipeline, before any config compilation has been performed. If there is no config, then this field will be empty.
     * 
     * @var string $source
     */
	#[\JMS\Serializer\Annotation\SerializedName('source')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $source;
    
	public function __construct()
	{
		$this->compiled = "";
		$this->compiledSetupConfig = null;
		$this->setupConfig = null;
		$this->source = "";
	}
}
