<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetProjectWorkflowTestMetrics200ApplicationJSONTestRunsTestCounts - Test counts for a given pipeline number
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetProjectWorkflowTestMetrics200ApplicationJSONTestRunsTestCounts
{
    /**
     * The number of tests with the error status
     * 
     * @var int $error
     */
	#[\JMS\Serializer\Annotation\SerializedName('error')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $error;
    
    /**
     * The number of tests with the failure status
     * 
     * @var int $failure
     */
	#[\JMS\Serializer\Annotation\SerializedName('failure')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $failure;
    
    /**
     * The number of tests with the skipped status
     * 
     * @var int $skipped
     */
	#[\JMS\Serializer\Annotation\SerializedName('skipped')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $skipped;
    
    /**
     * The number of tests with the success status
     * 
     * @var int $success
     */
	#[\JMS\Serializer\Annotation\SerializedName('success')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $success;
    
    /**
     * The total number of tests
     * 
     * @var int $total
     */
	#[\JMS\Serializer\Annotation\SerializedName('total')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $total;
    
	public function __construct()
	{
		$this->error = 0;
		$this->failure = 0;
		$this->skipped = 0;
		$this->success = 0;
		$this->total = 0;
	}
}
