<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetPipelineByIdResponse
{
	
    public string $contentType;
    
    /**
     * A pipeline object.
     * 
     * @var ?\CircleCi\Models\Operations\GetPipelineByIdPipeline $pipeline
     */
	
    public ?GetPipelineByIdPipeline $pipeline = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetPipelineByIdDefaultApplicationJSON $getPipelineByIdDefaultApplicationJSONObject
     */
	
    public ?GetPipelineByIdDefaultApplicationJSON $getPipelineByIdDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->pipeline = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getPipelineByIdDefaultApplicationJSONObject = null;
	}
}
