<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetProjectWorkflowRunsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A paginated list of recent workflow runs
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowRuns200ApplicationJSON $getProjectWorkflowRuns200ApplicationJSONObject
     */
	
    public ?GetProjectWorkflowRuns200ApplicationJSON $getProjectWorkflowRuns200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowRunsDefaultApplicationJSON $getProjectWorkflowRunsDefaultApplicationJSONObject
     */
	
    public ?GetProjectWorkflowRunsDefaultApplicationJSON $getProjectWorkflowRunsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getProjectWorkflowRuns200ApplicationJSONObject = null;
		$this->getProjectWorkflowRunsDefaultApplicationJSONObject = null;
	}
}
