<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetProjectWorkflowJobMetricsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A paginated list of summary metrics by workflow job.
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowJobMetrics200ApplicationJSON $getProjectWorkflowJobMetrics200ApplicationJSONObject
     */
	
    public ?GetProjectWorkflowJobMetrics200ApplicationJSON $getProjectWorkflowJobMetrics200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowJobMetricsDefaultApplicationJSON $getProjectWorkflowJobMetricsDefaultApplicationJSONObject
     */
	
    public ?GetProjectWorkflowJobMetricsDefaultApplicationJSON $getProjectWorkflowJobMetricsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getProjectWorkflowJobMetrics200ApplicationJSONObject = null;
		$this->getProjectWorkflowJobMetricsDefaultApplicationJSONObject = null;
	}
}
