<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetProjectWorkflowTestMetrics200ApplicationJSONTestRuns
{
    /**
     * The number of the pipeline associated with the provided test counts
     * 
     * @var int $pipelineNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('pipeline_number')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $pipelineNumber;
    
    /**
     * The success rate calculated from test counts
     * 
     * @var float $successRate
     */
	#[\JMS\Serializer\Annotation\SerializedName('success_rate')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $successRate;
    
    /**
     * Test counts for a given pipeline number
     * 
     * @var \CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONTestRunsTestCounts $testCounts
     */
	#[\JMS\Serializer\Annotation\SerializedName('test_counts')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONTestRunsTestCounts')]
    public GetProjectWorkflowTestMetrics200ApplicationJSONTestRunsTestCounts $testCounts;
    
    /**
     * The ID of the workflow associated with the provided test counts
     * 
     * @var mixed $workflowId
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow_id')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $workflowId;
    
	public function __construct()
	{
		$this->pipelineNumber = 0;
		$this->successRate = 0;
		$this->testCounts = new \CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONTestRunsTestCounts();
		$this->workflowId = null;
	}
}
