<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class GetProjectWorkflowMetricsRequest
{
    /**
     * Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
     * 
     * @var ?bool $allBranches
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=all-branches')]
    public ?bool $allBranches = null;
    
    /**
     * The name of a vcs branch. If not passed we will scope the API call to the default branch.
     * 
     * @var ?string $branch
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=branch')]
    public ?string $branch = null;
    
    /**
     * A token to retrieve the next page of results.
     * 
     * @var ?string $pageToken
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page-token')]
    public ?string $pageToken = null;
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     * 
     * @var string $projectSlug
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project-slug')]
    public string $projectSlug;
    
    /**
     * The time window used to calculate summary metrics.
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowMetricsReportingWindowEnum $reportingWindow
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=reporting-window')]
    public ?GetProjectWorkflowMetricsReportingWindowEnum $reportingWindow = null;
    
	public function __construct()
	{
		$this->allBranches = null;
		$this->branch = null;
		$this->pageToken = null;
		$this->projectSlug = "";
		$this->reportingWindow = null;
	}
}
