<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetProjectWorkflowMetrics200ApplicationJSONItemsMetrics - Metrics relating to a workflow's runs.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetProjectWorkflowMetrics200ApplicationJSONItemsMetrics
{
    /**
     * Metrics relating to the duration of runs for a workflow.
     * 
     * @var \CircleCi\Models\Operations\GetProjectWorkflowMetrics200ApplicationJSONItemsMetricsDurationMetrics $durationMetrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('duration_metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectWorkflowMetrics200ApplicationJSONItemsMetricsDurationMetrics')]
    public GetProjectWorkflowMetrics200ApplicationJSONItemsMetricsDurationMetrics $durationMetrics;
    
    /**
     * The number of failed runs.
     * 
     * @var int $failedRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('failed_runs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $failedRuns;
    
    /**
     * The mean time to recovery (mean time between failures and their next success) in seconds.
     * 
     * @var int $mttr
     */
	#[\JMS\Serializer\Annotation\SerializedName('mttr')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $mttr;
    
	#[\JMS\Serializer\Annotation\SerializedName('success_rate')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $successRate;
    
    /**
     * The number of successful runs.
     * 
     * @var int $successfulRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('successful_runs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $successfulRuns;
    
    /**
     * The average number of runs per day.
     * 
     * @var float $throughput
     */
	#[\JMS\Serializer\Annotation\SerializedName('throughput')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $throughput;
    
    /**
     * The total credits consumed by the workflow in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
     * 
     * @var int $totalCreditsUsed
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_credits_used')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalCreditsUsed;
    
    /**
     * The number of recovered workflow executions per day.
     * 
     * @var int $totalRecoveries
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_recoveries')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalRecoveries;
    
    /**
     * The total number of runs.
     * 
     * @var int $totalRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_runs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalRuns;
    
	public function __construct()
	{
		$this->durationMetrics = new \CircleCi\Models\Operations\GetProjectWorkflowMetrics200ApplicationJSONItemsMetricsDurationMetrics();
		$this->failedRuns = 0;
		$this->mttr = 0;
		$this->successRate = 0;
		$this->successfulRuns = 0;
		$this->throughput = 0;
		$this->totalCreditsUsed = 0;
		$this->totalRecoveries = 0;
		$this->totalRuns = 0;
	}
}
