<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowData
{
    /**
     * Metrics aggregated across a workflow or branchfor a project.
     * 
     * @var \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataMetrics $metrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataMetrics')]
    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataMetrics $metrics;
    
    /**
     * Trends aggregated across a workflow or branch for a project.
     * 
     * @var \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataTrends $trends
     */
	#[\JMS\Serializer\Annotation\SerializedName('trends')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataTrends')]
    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataTrends $trends;
    
    /**
     * The name of the workflow.
     * 
     * @var string $workflowName
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workflowName;
    
	public function __construct()
	{
		$this->metrics = new \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataMetrics();
		$this->trends = new \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataTrends();
		$this->workflowName = "";
	}
}
