<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of trigger. */
enum GetPipelineByNumberPipelineTriggerTypeEnum: string
{
    case SCHEDULED_PIPELINE = 'scheduled_pipeline';
    case EXPLICIT = 'explicit';
    case API = 'api';
    case WEBHOOK = 'webhook';
}
