<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetProjectWorkflowsPageDataWorkflowNames - The names of workflows to include in workflow-level metrics.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetProjectWorkflowsPageDataWorkflowNames
{
	public function __construct()
	{
	}
}
