<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The VCS provider */
enum GetProjectBySlugProjectVcsInfoProviderEnum: string
{
    case BITBUCKET = 'Bitbucket';
    case CIRCLE_CI = 'CircleCI';
    case GIT_HUB = 'GitHub';
}
