<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetProjectWorkflowsPageData200ApplicationJSONProjectData - Metrics and trends data aggregated for a given project.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetProjectWorkflowsPageData200ApplicationJSONProjectData
{
    /**
     * Metrics aggregated across all workflows and branches for a project.
     * 
     * @var \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectDataMetrics $metrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectDataMetrics')]
    public GetProjectWorkflowsPageData200ApplicationJSONProjectDataMetrics $metrics;
    
    /**
     * Metric trends aggregated across all workflows and branches for a project.
     * 
     * @var \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectDataTrends $trends
     */
	#[\JMS\Serializer\Annotation\SerializedName('trends')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectDataTrends')]
    public GetProjectWorkflowsPageData200ApplicationJSONProjectDataTrends $trends;
    
	public function __construct()
	{
		$this->metrics = new \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectDataMetrics();
		$this->trends = new \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectDataTrends();
	}
}
