<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetProjectWorkflowTestMetrics200ApplicationJSON - Project level test metrics response
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetProjectWorkflowTestMetrics200ApplicationJSON
{
    /**
     * The average number of tests executed per run
     * 
     * @var int $averageTestCount
     */
	#[\JMS\Serializer\Annotation\SerializedName('average_test_count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $averageTestCount;
    
    /**
     * Metrics for the most frequently failing tests
     * 
     * @var array<\CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONMostFailedTests> $mostFailedTests
     */
	#[\JMS\Serializer\Annotation\SerializedName('most_failed_tests')]
    #[\JMS\Serializer\Annotation\Type('array<CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONMostFailedTests>')]
    public array $mostFailedTests;
    
    /**
     * The number of tests with the same success rate being omitted from most_failed_tests
     * 
     * @var int $mostFailedTestsExtra
     */
	#[\JMS\Serializer\Annotation\SerializedName('most_failed_tests_extra')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $mostFailedTestsExtra;
    
    /**
     * Metrics for the slowest running tests
     * 
     * @var array<\CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests> $slowestTests
     */
	#[\JMS\Serializer\Annotation\SerializedName('slowest_tests')]
    #[\JMS\Serializer\Annotation\Type('array<CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests>')]
    public array $slowestTests;
    
    /**
     * The number of tests with the same duration rate being omitted from slowest_tests
     * 
     * @var int $slowestTestsExtra
     */
	#[\JMS\Serializer\Annotation\SerializedName('slowest_tests_extra')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $slowestTestsExtra;
    
    /**
     * Test counts grouped by pipeline number and workflow id
     * 
     * @var array<\CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONTestRuns> $testRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('test_runs')]
    #[\JMS\Serializer\Annotation\Type('array<CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSONTestRuns>')]
    public array $testRuns;
    
    /**
     * The total number of test runs
     * 
     * @var int $totalTestRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_test_runs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalTestRuns;
    
	public function __construct()
	{
		$this->averageTestCount = 0;
		$this->mostFailedTests = [];
		$this->mostFailedTestsExtra = 0;
		$this->slowestTests = [];
		$this->slowestTestsExtra = 0;
		$this->testRuns = [];
		$this->totalTestRuns = 0;
	}
}
