<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The time window used to calculate summary metrics. */
enum GetProjectWorkflowJobMetricsReportingWindow: string
{
    case Last7Days = 'last-7-days';
    case Last90Days = 'last-90-days';
    case Last24Hours = 'last-24-hours';
    case Last30Days = 'last-30-days';
    case Last60Days = 'last-60-days';
}
