<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetProjectWorkflowMetricsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A paginated list of summary metrics by workflow
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowMetrics200ApplicationJSON $getProjectWorkflowMetrics200ApplicationJSONObject
     */
	
    public ?GetProjectWorkflowMetrics200ApplicationJSON $getProjectWorkflowMetrics200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowMetricsDefaultApplicationJSON $getProjectWorkflowMetricsDefaultApplicationJSONObject
     */
	
    public ?GetProjectWorkflowMetricsDefaultApplicationJSON $getProjectWorkflowMetricsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getProjectWorkflowMetrics200ApplicationJSONObject = null;
		$this->getProjectWorkflowMetricsDefaultApplicationJSONObject = null;
	}
}
