<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The time window used to calculate summary metrics. */
enum GetProjectWorkflowJobMetricsReportingWindowEnum: string
{
    case LAST7_DAYS = 'last-7-days';
    case LAST90_DAYS = 'last-90-days';
    case LAST24_HOURS = 'last-24-hours';
    case LAST30_DAYS = 'last-30-days';
    case LAST60_DAYS = 'last-60-days';
}
