<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetProjectBySlugProject - NOTE: The definition of Project is subject to change.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetProjectBySlugProject
{
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The name of the project
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The id of the organization the project belongs to
     * 
     * @var string $organizationId
     */
	#[\JMS\Serializer\Annotation\SerializedName('organization_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $organizationId;
    
    /**
     * The name of the organization the project belongs to
     * 
     * @var string $organizationName
     */
	#[\JMS\Serializer\Annotation\SerializedName('organization_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $organizationName;
    
    /**
     * The slug of the organization the project belongs to
     * 
     * @var string $organizationSlug
     */
	#[\JMS\Serializer\Annotation\SerializedName('organization_slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $organizationSlug;
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     * 
     * @var string $slug
     */
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
    /**
     * Information about the VCS that hosts the project source code.
     * 
     * @var \CircleCi\Models\Operations\GetProjectBySlugProjectVcsInfo $vcsInfo
     */
	#[\JMS\Serializer\Annotation\SerializedName('vcs_info')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectBySlugProjectVcsInfo')]
    public GetProjectBySlugProjectVcsInfo $vcsInfo;
    
	public function __construct()
	{
		$this->id = "";
		$this->name = "";
		$this->organizationId = "";
		$this->organizationName = "";
		$this->organizationSlug = "";
		$this->slug = "";
		$this->vcsInfo = new \CircleCi\Models\Operations\GetProjectBySlugProjectVcsInfo();
	}
}
