<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataMetrics - Metrics aggregated across a workflow or branchfor a project.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataMetrics
{
    /**
     * The 95th percentile duration among a group of workflow runs.
     * 
     * @var float $p95DurationSecs
     */
	#[\JMS\Serializer\Annotation\SerializedName('p95_duration_secs')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $p95DurationSecs;
    
	#[\JMS\Serializer\Annotation\SerializedName('success_rate')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $successRate;
    
    /**
     * The total credits consumed over the current timeseries interval.
     * 
     * @var int $totalCreditsUsed
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_credits_used')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalCreditsUsed;
    
    /**
     * The total number of runs.
     * 
     * @var int $totalRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_runs')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalRuns;
    
	public function __construct()
	{
		$this->p95DurationSecs = 0;
		$this->successRate = 0;
		$this->totalCreditsUsed = 0;
		$this->totalRuns = 0;
	}
}
