<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchData
{
    /**
     * The VCS branch of a workflow's trigger.
     * 
     * @var string $branch
     */
	#[\JMS\Serializer\Annotation\SerializedName('branch')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $branch;
    
    /**
     * Metrics aggregated across a workflow or branchfor a project.
     * 
     * @var \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataMetrics $metrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataMetrics')]
    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataMetrics $metrics;
    
    /**
     * Trends aggregated across a workflow or branch for a project.
     * 
     * @var \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataTrends $trends
     */
	#[\JMS\Serializer\Annotation\SerializedName('trends')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataTrends')]
    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataTrends $trends;
    
    /**
     * The name of the workflow.
     * 
     * @var string $workflowName
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workflowName;
    
	public function __construct()
	{
		$this->branch = "";
		$this->metrics = new \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataMetrics();
		$this->trends = new \CircleCi\Models\Operations\GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowBranchDataTrends();
		$this->workflowName = "";
	}
}
