<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The VCS provider */
enum GetProjectBySlugProjectVcsInfoProvider: string
{
    case Bitbucket = 'Bitbucket';
    case CircleCI = 'CircleCI';
    case GitHub = 'GitHub';
}
