<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetProjectWorkflowTestMetricsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A list of test metrics by workflow
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowTestMetrics200ApplicationJSON $getProjectWorkflowTestMetrics200ApplicationJSONObject
     */
	
    public ?GetProjectWorkflowTestMetrics200ApplicationJSON $getProjectWorkflowTestMetrics200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetProjectWorkflowTestMetricsDefaultApplicationJSON $getProjectWorkflowTestMetricsDefaultApplicationJSONObject
     */
	
    public ?GetProjectWorkflowTestMetricsDefaultApplicationJSON $getProjectWorkflowTestMetricsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getProjectWorkflowTestMetrics200ApplicationJSONObject = null;
		$this->getProjectWorkflowTestMetricsDefaultApplicationJSONObject = null;
	}
}
