<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** Day in a week, in three letters format */
enum GetScheduleByIdScheduleTimetable1DaysOfWeek: string
{
    case Tue = 'TUE';
    case Sat = 'SAT';
    case Sun = 'SUN';
    case Mon = 'MON';
    case Thu = 'THU';
    case Wed = 'WED';
    case Fri = 'FRI';
}
