<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetScheduleByIdSchedule - A schedule response
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetScheduleByIdSchedule
{
    /**
     * The attribution actor who will run the scheduled pipeline.
     * 
     * @var \CircleCi\Models\Operations\GetScheduleByIdScheduleUser $actor
     */
	#[\JMS\Serializer\Annotation\SerializedName('actor')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetScheduleByIdScheduleUser')]
    public GetScheduleByIdScheduleUser $actor;
    
    /**
     * The date and time the pipeline was created.
     * 
     * @var \DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created-at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
    /**
     * Description of the schedule.
     * 
     * @var string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
    /**
     * The unique ID of the schedule.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * Name of the schedule.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Pipeline parameters represented as key-value pairs. Must contain branch or tag.
     * 
     * @var array<string, mixed> $parameters
     */
	#[\JMS\Serializer\Annotation\SerializedName('parameters')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    public array $parameters;
    
    /**
     * The project-slug for the schedule
     * 
     * @var string $projectSlug
     */
	#[\JMS\Serializer\Annotation\SerializedName('project-slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $projectSlug;
    
    /**
     * Timetable that specifies when a schedule triggers.
     * 
     * @var mixed $timetable
     */
	#[\JMS\Serializer\Annotation\SerializedName('timetable')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $timetable;
    
    /**
     * The date and time the pipeline was last updated.
     * 
     * @var \DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated-at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $updatedAt;
    
	public function __construct()
	{
		$this->actor = new \CircleCi\Models\Operations\GetScheduleByIdScheduleUser();
		$this->createdAt = new \DateTime();
		$this->description = "";
		$this->id = "";
		$this->name = "";
		$this->parameters = [];
		$this->projectSlug = "";
		$this->timetable = null;
		$this->updatedAt = new \DateTime();
	}
}
