<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetTestsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A paginated list of test results.
     * 
     * @var ?\CircleCi\Models\Operations\GetTestsTestsResponse $testsResponse
     */
	
    public ?GetTestsTestsResponse $testsResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetTestsDefaultApplicationJSON $getTestsDefaultApplicationJSONObject
     */
	
    public ?GetTestsDefaultApplicationJSON $getTestsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->testsResponse = null;
		$this->getTestsDefaultApplicationJSONObject = null;
	}
}
