<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetTestsTestsResponseItems
{
    /**
     * The programmatic location of the test.
     * 
     * @var string $classname
     */
	#[\JMS\Serializer\Annotation\SerializedName('classname')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $classname;
    
    /**
     * The file in which the test is defined.
     * 
     * @var string $file
     */
	#[\JMS\Serializer\Annotation\SerializedName('file')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $file;
    
    /**
     * The failure message associated with the test.
     * 
     * @var string $message
     */
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
    /**
     * The name of the test.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Indication of whether the test succeeded.
     * 
     * @var string $result
     */
	#[\JMS\Serializer\Annotation\SerializedName('result')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $result;
    
    /**
     * The time it took to run the test in seconds
     * 
     * @var float $runTime
     */
	#[\JMS\Serializer\Annotation\SerializedName('run_time')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $runTime;
    
    /**
     * The program that generated the test results
     * 
     * @var string $source
     */
	#[\JMS\Serializer\Annotation\SerializedName('source')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $source;
    
	public function __construct()
	{
		$this->classname = "";
		$this->file = "";
		$this->message = "";
		$this->name = "";
		$this->result = "";
		$this->runTime = 0;
		$this->source = "";
	}
}
