<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetUserResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * User login information.
     * 
     * @var ?\CircleCi\Models\Operations\GetUserUser $user
     */
	
    public ?GetUserUser $user = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetUserDefaultApplicationJSON $getUserDefaultApplicationJSONObject
     */
	
    public ?GetUserDefaultApplicationJSON $getUserDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->user = null;
		$this->getUserDefaultApplicationJSONObject = null;
	}
}
