<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetWorkflowSummary200ApplicationJSON - Workflow level aggregated metrics and trends response
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetWorkflowSummary200ApplicationJSON
{
    /**
     * Metrics aggregated across a workflow for a given time window.
     * 
     * @var \CircleCi\Models\Operations\GetWorkflowSummary200ApplicationJSONMetrics $metrics
     */
	#[\JMS\Serializer\Annotation\SerializedName('metrics')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetWorkflowSummary200ApplicationJSONMetrics')]
    public GetWorkflowSummary200ApplicationJSONMetrics $metrics;
    
    /**
     * Trends for aggregated metrics across a workflow for a given time window.
     * 
     * @var \CircleCi\Models\Operations\GetWorkflowSummary200ApplicationJSONTrends $trends
     */
	#[\JMS\Serializer\Annotation\SerializedName('trends')]
    #[\JMS\Serializer\Annotation\Type('CircleCi\Models\Operations\GetWorkflowSummary200ApplicationJSONTrends')]
    public GetWorkflowSummary200ApplicationJSONTrends $trends;
    
    /**
     * A list of all the workflow names for a given project.
     * 
     * @var array<string> $workflowNames
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow_names')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $workflowNames;
    
	public function __construct()
	{
		$this->metrics = new \CircleCi\Models\Operations\GetWorkflowSummary200ApplicationJSONMetrics();
		$this->trends = new \CircleCi\Models\Operations\GetWorkflowSummary200ApplicationJSONTrends();
		$this->workflowNames = [];
	}
}
