<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class GetWorkflowSummaryRequest
{
    /**
     * Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
     * 
     * @var ?bool $allBranches
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=all-branches')]
    public ?bool $allBranches = null;
    
    /**
     * The names of VCS branches to include in branch-level workflow metrics.
     * 
     * @var ?\CircleCi\Models\Operations\GetWorkflowSummaryBranches $branches
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=branches')]
    public ?GetWorkflowSummaryBranches $branches = null;
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     * 
     * @var string $projectSlug
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project-slug')]
    public string $projectSlug;
    
    /**
     * The name of the workflow.
     * 
     * @var string $workflowName
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=workflow-name')]
    public string $workflowName;
    
	public function __construct()
	{
		$this->allBranches = null;
		$this->branches = null;
		$this->projectSlug = "";
		$this->workflowName = "";
	}
}
