<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetWorkflowSummary200ApplicationJSONTrends - Trends for aggregated metrics across a workflow for a given time window.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetWorkflowSummary200ApplicationJSONTrends
{
    /**
     * The trend value for number of failed runs.
     * 
     * @var float $failedRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('failed_runs')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $failedRuns;
    
    /**
     * Trend value for the 50th percentile duration for a workflow for a given time window.
     * 
     * @var float $medianDurationSecs
     */
	#[\JMS\Serializer\Annotation\SerializedName('median_duration_secs')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $medianDurationSecs;
    
    /**
     * trend for mean time to recovery (mean time between failures and their next success).
     * 
     * @var float $mttr
     */
	#[\JMS\Serializer\Annotation\SerializedName('mttr')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $mttr;
    
    /**
     * Trend value for the 95th percentile duration for a workflow for a given time window.
     * 
     * @var float $p95DurationSecs
     */
	#[\JMS\Serializer\Annotation\SerializedName('p95_duration_secs')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $p95DurationSecs;
    
    /**
     * The trend value for the success rate.
     * 
     * @var float $successRate
     */
	#[\JMS\Serializer\Annotation\SerializedName('success_rate')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $successRate;
    
    /**
     * Trend value for the average number of runs per day.
     * 
     * @var float $throughput
     */
	#[\JMS\Serializer\Annotation\SerializedName('throughput')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $throughput;
    
    /**
     * The trend value for total credits consumed.
     * 
     * @var float $totalCreditsUsed
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_credits_used')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $totalCreditsUsed;
    
    /**
     * The trend value for total number of runs.
     * 
     * @var float $totalRuns
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_runs')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $totalRuns;
    
	public function __construct()
	{
		$this->failedRuns = 0;
		$this->medianDurationSecs = 0;
		$this->mttr = 0;
		$this->p95DurationSecs = 0;
		$this->successRate = 0;
		$this->throughput = 0;
		$this->totalCreditsUsed = 0;
		$this->totalRuns = 0;
	}
}
