<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


enum GetWebhookByIdWebhookEvents: string
{
    case WorkflowCompleted = 'workflow-completed';
    case JobCompleted = 'job-completed';
}
