<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * GetWorkflowSummaryBranches - The names of VCS branches to include in branch-level workflow metrics.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class GetWorkflowSummaryBranches
{
	public function __construct()
	{
	}
}
