<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetWorkflowByIdResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A workflow object.
     * 
     * @var ?\CircleCi\Models\Operations\GetWorkflowByIdWorkflow $workflow
     */
	
    public ?GetWorkflowByIdWorkflow $workflow = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetWorkflowByIdDefaultApplicationJSON $getWorkflowByIdDefaultApplicationJSONObject
     */
	
    public ?GetWorkflowByIdDefaultApplicationJSON $getWorkflowByIdDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->workflow = null;
		$this->getWorkflowByIdDefaultApplicationJSONObject = null;
	}
}
