<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class GetWebhooksResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A list of webhooks
     * 
     * @var ?\CircleCi\Models\Operations\GetWebhooks200ApplicationJSON $getWebhooks200ApplicationJSONObject
     */
	
    public ?GetWebhooks200ApplicationJSON $getWebhooks200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\GetWebhooksDefaultApplicationJSON $getWebhooksDefaultApplicationJSONObject
     */
	
    public ?GetWebhooksDefaultApplicationJSON $getWebhooksDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getWebhooks200ApplicationJSONObject = null;
		$this->getWebhooksDefaultApplicationJSONObject = null;
	}
}
