<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The current status of the workflow. */
enum GetWorkflowByIdWorkflowStatus: string
{
    case Success = 'success';
    case Running = 'running';
    case NotRun = 'not_run';
    case Failed = 'failed';
    case Error = 'error';
    case Failing = 'failing';
    case OnHold = 'on_hold';
    case Canceled = 'canceled';
    case Unauthorized = 'unauthorized';
}
