<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class ListCheckoutKeysResponse
{
    /**
     * A sequence of checkout keys.
     * 
     * @var ?\CircleCi\Models\Operations\ListCheckoutKeysCheckoutKeyListResponse $checkoutKeyListResponse
     */
	
    public ?ListCheckoutKeysCheckoutKeyListResponse $checkoutKeyListResponse = null;
    
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\ListCheckoutKeysDefaultApplicationJSON $listCheckoutKeysDefaultApplicationJSONObject
     */
	
    public ?ListCheckoutKeysDefaultApplicationJSON $listCheckoutKeysDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->checkoutKeyListResponse = null;
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listCheckoutKeysDefaultApplicationJSONObject = null;
	}
}
