<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class ListWorkflowsByPipelineIdRequest
{
    /**
     * A token to retrieve the next page of results.
     * 
     * @var ?string $pageToken
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page-token')]
    public ?string $pageToken = null;
    
    /**
     * The unique ID of the pipeline.
     * 
     * @var string $pipelineId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=pipeline-id')]
    public string $pipelineId;
    
	public function __construct()
	{
		$this->pageToken = null;
		$this->pipelineId = "";
	}
}
