<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class ListWorkflowJobsResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A paginated sequence of jobs.
     * 
     * @var ?\CircleCi\Models\Operations\ListWorkflowJobsWorkflowJobListResponse $workflowJobListResponse
     */
	
    public ?ListWorkflowJobsWorkflowJobListResponse $workflowJobListResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\ListWorkflowJobsDefaultApplicationJSON $listWorkflowJobsDefaultApplicationJSONObject
     */
	
    public ?ListWorkflowJobsDefaultApplicationJSON $listWorkflowJobsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->workflowJobListResponse = null;
		$this->listWorkflowJobsDefaultApplicationJSONObject = null;
	}
}
