<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class ListSchedulesForProjectResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A sequence of schedules.
     * 
     * @var ?\CircleCi\Models\Operations\ListSchedulesForProject200ApplicationJSON $listSchedulesForProject200ApplicationJSONObject
     */
	
    public ?ListSchedulesForProject200ApplicationJSON $listSchedulesForProject200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\ListSchedulesForProjectDefaultApplicationJSON $listSchedulesForProjectDefaultApplicationJSONObject
     */
	
    public ?ListSchedulesForProjectDefaultApplicationJSON $listSchedulesForProjectDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listSchedulesForProject200ApplicationJSONObject = null;
		$this->listSchedulesForProjectDefaultApplicationJSONObject = null;
	}
}
