<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class ListEnvironmentVariablesFromContextRequest
{
    /**
     * ID of the context (UUID)
     * 
     * @var string $contextId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=context-id')]
    public string $contextId;
    
    /**
     * A token to retrieve the next page of results.
     * 
     * @var ?string $pageToken
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page-token')]
    public ?string $pageToken = null;
    
	public function __construct()
	{
		$this->contextId = "";
		$this->pageToken = null;
	}
}
