<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class ListEnvironmentVariablesFromContextResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A paginated list of environment variables
     * 
     * @var ?\CircleCi\Models\Operations\ListEnvironmentVariablesFromContext200ApplicationJSON $listEnvironmentVariablesFromContext200ApplicationJSONObject
     */
	
    public ?ListEnvironmentVariablesFromContext200ApplicationJSON $listEnvironmentVariablesFromContext200ApplicationJSONObject = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\ListEnvironmentVariablesFromContextDefaultApplicationJSON $listEnvironmentVariablesFromContextDefaultApplicationJSONObject
     */
	
    public ?ListEnvironmentVariablesFromContextDefaultApplicationJSON $listEnvironmentVariablesFromContextDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listEnvironmentVariablesFromContext200ApplicationJSONObject = null;
		$this->listEnvironmentVariablesFromContextDefaultApplicationJSONObject = null;
	}
}
