<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class ListEnvVarsResponse
{
	
    public string $contentType;
    
    /**
     * A sequence of environment variables.
     * 
     * @var ?\CircleCi\Models\Operations\ListEnvVarsEnvironmentVariableListResponse $environmentVariableListResponse
     */
	
    public ?ListEnvVarsEnvironmentVariableListResponse $environmentVariableListResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\ListEnvVarsDefaultApplicationJSON $listEnvVarsDefaultApplicationJSONObject
     */
	
    public ?ListEnvVarsDefaultApplicationJSON $listEnvVarsDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->environmentVariableListResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listEnvVarsDefaultApplicationJSONObject = null;
	}
}
