<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of job. */
enum ListWorkflowJobsWorkflowJobListResponseJobType: string
{
    case Build = 'build';
    case Approval = 'approval';
}
