<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * ListWorkflowJobsWorkflowJobListResponseJob - Job
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class ListWorkflowJobsWorkflowJobListResponseJob
{
    /**
     * The unique ID of the job.
     * 
     * @var ?string $approvalRequestId
     */
	#[\JMS\Serializer\Annotation\SerializedName('approval_request_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $approvalRequestId = null;
    
    /**
     * The unique ID of the user.
     * 
     * @var ?string $approvedBy
     */
	#[\JMS\Serializer\Annotation\SerializedName('approved_by')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $approvedBy = null;
    
    /**
     * The unique ID of the user.
     * 
     * @var ?string $canceledBy
     */
	#[\JMS\Serializer\Annotation\SerializedName('canceled_by')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $canceledBy = null;
    
    /**
     * A sequence of the unique job IDs for the jobs that this job depends upon in the workflow.
     * 
     * @var array<string> $dependencies
     */
	#[\JMS\Serializer\Annotation\SerializedName('dependencies')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $dependencies;
    
    /**
     * The unique ID of the job.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * The number of the job.
     * 
     * @var ?int $jobNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('job_number')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $jobNumber = null;
    
    /**
     * The name of the job.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The project-slug for the job.
     * 
     * @var string $projectSlug
     */
	#[\JMS\Serializer\Annotation\SerializedName('project_slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $projectSlug;
    
    /**
     * The date and time the job started.
     * 
     * @var \DateTime $startedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('started_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $startedAt;
    
    /**
     * The current status of the job.
     * 
     * @var \CircleCi\Models\Operations\ListWorkflowJobsWorkflowJobListResponseJobStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<CircleCi\Models\Operations\ListWorkflowJobsWorkflowJobListResponseJobStatus>')]
    public ListWorkflowJobsWorkflowJobListResponseJobStatus $status;
    
    /**
     * The time when the job stopped.
     * 
     * @var ?\DateTime $stoppedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('stopped_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $stoppedAt = null;
    
    /**
     * The type of job.
     * 
     * @var \CircleCi\Models\Operations\ListWorkflowJobsWorkflowJobListResponseJobType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<CircleCi\Models\Operations\ListWorkflowJobsWorkflowJobListResponseJobType>')]
    public ListWorkflowJobsWorkflowJobListResponseJobType $type;
    
	public function __construct()
	{
		$this->approvalRequestId = null;
		$this->approvedBy = null;
		$this->canceledBy = null;
		$this->dependencies = [];
		$this->id = "";
		$this->jobNumber = null;
		$this->name = "";
		$this->projectSlug = "";
		$this->startedAt = new \DateTime();
		$this->status = \CircleCi\Models\Operations\ListWorkflowJobsWorkflowJobListResponseJobStatus::Success;
		$this->stoppedAt = null;
		$this->type = \CircleCi\Models\Operations\ListWorkflowJobsWorkflowJobListResponseJobType::Build;
	}
}
