<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class ListMyPipelinesResponse
{
	
    public string $contentType;
    
    /**
     * A sequence of pipelines.
     * 
     * @var ?\CircleCi\Models\Operations\ListMyPipelinesPipelineListResponse $pipelineListResponse
     */
	
    public ?ListMyPipelinesPipelineListResponse $pipelineListResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\ListMyPipelinesDefaultApplicationJSON $listMyPipelinesDefaultApplicationJSONObject
     */
	
    public ?ListMyPipelinesDefaultApplicationJSON $listMyPipelinesDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->pipelineListResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listMyPipelinesDefaultApplicationJSONObject = null;
	}
}
