<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class ListContextsRequest
{
    /**
     * The unique ID of the owner of the context. Specify either this or owner-slug.
     * 
     * @var ?string $ownerId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=owner-id')]
    public ?string $ownerId = null;
    
    /**
     * A string that represents an organization. Specify either this or owner-id. Cannot be used for accounts.
     * 
     * @var ?string $ownerSlug
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=owner-slug')]
    public ?string $ownerSlug = null;
    
    /**
     * The type of the owner. Defaults to "organization". Accounts are only used as context owners in server.
     * 
     * @var ?\CircleCi\Models\Operations\ListContextsOwnerTypeEnum $ownerType
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=owner-type')]
    public ?ListContextsOwnerTypeEnum $ownerType = null;
    
    /**
     * A token to retrieve the next page of results.
     * 
     * @var ?string $pageToken
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page-token')]
    public ?string $pageToken = null;
    
	public function __construct()
	{
		$this->ownerId = null;
		$this->ownerSlug = null;
		$this->ownerType = null;
		$this->pageToken = null;
	}
}
