<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of job. */
enum ListWorkflowJobsWorkflowJobListResponseJobTypeEnum: string
{
    case BUILD = 'build';
    case APPROVAL = 'approval';
}
