<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The type of trigger. */
enum ListPipelinesForProjectPipelineListResponsePipelineTriggerType: string
{
    case ScheduledPipeline = 'scheduled_pipeline';
    case Explicit = 'explicit';
    case Api = 'api';
    case Webhook = 'webhook';
}
