<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The current status of the job. */
enum ListWorkflowJobsWorkflowJobListResponseJobStatus: string
{
    case Success = 'success';
    case Running = 'running';
    case NotRun = 'not_run';
    case Failed = 'failed';
    case Retried = 'retried';
    case Queued = 'queued';
    case NotRunning = 'not_running';
    case InfrastructureFail = 'infrastructure_fail';
    case Timedout = 'timedout';
    case OnHold = 'on_hold';
    case TerminatedUnknown = 'terminated-unknown';
    case Blocked = 'blocked';
    case Canceled = 'canceled';
    case Unauthorized = 'unauthorized';
}
