<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** Tag used for the workflow */
enum ListWorkflowsByPipelineIdWorkflowListResponseWorkflowTag: string
{
    case SETUP = 'setup';
}
