<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The current status of the workflow. */
enum ListWorkflowsByPipelineIdWorkflowListResponseWorkflowStatus: string
{
    case SUCCESS = 'success';
    case RUNNING = 'running';
    case NOT_RUN = 'not_run';
    case FAILED = 'failed';
    case ERROR = 'error';
    case FAILING = 'failing';
    case ON_HOLD = 'on_hold';
    case CANCELED = 'canceled';
    case UNAUTHORIZED = 'unauthorized';
}
