<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class TriggerPipelineResponse
{
	
    public string $contentType;
    
    /**
     * The created pipeline.
     * 
     * @var ?\CircleCi\Models\Operations\TriggerPipelinePipelineCreation $pipelineCreation
     */
	
    public ?TriggerPipelinePipelineCreation $pipelineCreation = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\TriggerPipelineDefaultApplicationJSON $triggerPipelineDefaultApplicationJSONObject
     */
	
    public ?TriggerPipelineDefaultApplicationJSON $triggerPipelineDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->pipelineCreation = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->triggerPipelineDefaultApplicationJSONObject = null;
	}
}
