<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class UpdateWebhookResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * A webhook
     * 
     * @var ?\CircleCi\Models\Operations\UpdateWebhookWebhook $webhook
     */
	
    public ?UpdateWebhookWebhook $webhook = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\UpdateWebhookDefaultApplicationJSON $updateWebhookDefaultApplicationJSONObject
     */
	
    public ?UpdateWebhookDefaultApplicationJSON $updateWebhookDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->webhook = null;
		$this->updateWebhookDefaultApplicationJSONObject = null;
	}
}
