<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


class UpdateScheduleResponse
{
	
    public string $contentType;
    
    /**
     * A schedule object.
     * 
     * @var ?\CircleCi\Models\Operations\UpdateScheduleSchedule $schedule
     */
	
    public ?UpdateScheduleSchedule $schedule = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Error response.
     * 
     * @var ?\CircleCi\Models\Operations\UpdateScheduleDefaultApplicationJSON $updateScheduleDefaultApplicationJSONObject
     */
	
    public ?UpdateScheduleDefaultApplicationJSON $updateScheduleDefaultApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->schedule = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->updateScheduleDefaultApplicationJSONObject = null;
	}
}
