<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;

use \CircleCi\Utils\SpeakeasyMetadata;
class UpdateWebhookRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?UpdateWebhookRequestBody $requestBody = null;
    
    /**
     * ID of the webhook (UUID)
     * 
     * @var string $webhookId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=webhook-id')]
    public string $webhookId;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->webhookId = "";
	}
}
