<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * UpdateScheduleUpdateScheduleParametersTimetable - Timetable that specifies when a schedule triggers.
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class UpdateScheduleUpdateScheduleParametersTimetable
{
    /**
     * Days in a month in which the schedule triggers. This is mutually exclusive with days in a week.
     * 
     * @var ?array<int> $daysOfMonth
     */
	#[\JMS\Serializer\Annotation\SerializedName('days-of-month')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $daysOfMonth = null;
    
    /**
     * Days in a week in which the schedule triggers.
     * 
     * @var ?array<\CircleCi\Models\Operations\UpdateScheduleUpdateScheduleParametersTimetableDaysOfWeek> $daysOfWeek
     */
	#[\JMS\Serializer\Annotation\SerializedName('days-of-week')]
    #[\JMS\Serializer\Annotation\Type('array<enum<CircleCi\Models\Operations\UpdateScheduleUpdateScheduleParametersTimetableDaysOfWeek>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $daysOfWeek = null;
    
    /**
     * Hours in a day in which the schedule triggers.
     * 
     * @var ?array<int> $hoursOfDay
     */
	#[\JMS\Serializer\Annotation\SerializedName('hours-of-day')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $hoursOfDay = null;
    
    /**
     * Months in which the schedule triggers.
     * 
     * @var ?array<\CircleCi\Models\Operations\UpdateScheduleUpdateScheduleParametersTimetableMonths> $months
     */
	#[\JMS\Serializer\Annotation\SerializedName('months')]
    #[\JMS\Serializer\Annotation\Type('array<enum<CircleCi\Models\Operations\UpdateScheduleUpdateScheduleParametersTimetableMonths>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $months = null;
    
    /**
     * Number of times a schedule triggers per hour, value must be between 1 and 60
     * 
     * @var ?int $perHour
     */
	#[\JMS\Serializer\Annotation\SerializedName('per-hour')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $perHour = null;
    
	public function __construct()
	{
		$this->daysOfMonth = null;
		$this->daysOfWeek = null;
		$this->hoursOfDay = null;
		$this->months = null;
		$this->perHour = null;
	}
}
