<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/**
 * UpdateWebhookRequestBody - The parameters for an update webhook request
 * 
 * @package CircleCi\Models\Operations
 * @access public
 */
class UpdateWebhookRequestBody
{
    /**
     * Events that will trigger the webhook
     * 
     * @var ?array<\CircleCi\Models\Operations\UpdateWebhookRequestBodyEvents> $events
     */
	#[\JMS\Serializer\Annotation\SerializedName('events')]
    #[\JMS\Serializer\Annotation\Type('array<enum<CircleCi\Models\Operations\UpdateWebhookRequestBodyEvents>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $events = null;
    
    /**
     * Name of the webhook
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Secret used to build an HMAC hash of the payload and passed as a header in the webhook request
     * 
     * @var ?string $signingSecret
     */
	#[\JMS\Serializer\Annotation\SerializedName('signing-secret')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $signingSecret = null;
    
    /**
     * URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
     * 
     * @var ?string $url
     */
	#[\JMS\Serializer\Annotation\SerializedName('url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $url = null;
    
    /**
     * Whether to enforce TLS certificate verification when delivering the webhook
     * 
     * @var ?bool $verifyTls
     */
	#[\JMS\Serializer\Annotation\SerializedName('verify-tls')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $verifyTls = null;
    
	public function __construct()
	{
		$this->events = null;
		$this->name = null;
		$this->signingSecret = null;
		$this->url = null;
		$this->verifyTls = null;
	}
}
