<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** Month, in three letters format. */
enum UpdateScheduleScheduleTimetable2Months: string
{
    case Mar = 'MAR';
    case Nov = 'NOV';
    case Dec = 'DEC';
    case Jun = 'JUN';
    case May = 'MAY';
    case Oct = 'OCT';
    case Feb = 'FEB';
    case Apr = 'APR';
    case Sep = 'SEP';
    case Aug = 'AUG';
    case Jan = 'JAN';
    case Jul = 'JUL';
}
