<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Operations;


/** The attribution-actor of the scheduled pipeline. */
enum UpdateScheduleUpdateScheduleParametersAttributionActor: string
{
    case Current = 'current';
    case System = 'system';
}
