<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Shared;

use \CircleCi\Utils\SpeakeasyMetadata;
class SchemeBasicAuth
{
	#[SpeakeasyMetadata('security:name=password')]
    public string $password;
    
	#[SpeakeasyMetadata('security:name=username')]
    public string $username;
    
	public function __construct()
	{
		$this->password = "";
		$this->username = "";
	}
}
