<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace CircleCi\Models\Shared;

use \CircleCi\Utils\SpeakeasyMetadata;
class Security
{
	#[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=Circle-Token')]
    public ?string $apiKeyHeader = null;
    
	#[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=query,name=circle-token')]
    public ?string $apiKeyQuery = null;
    
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=basic')]
    public ?SchemeBasicAuth $basicAuth = null;
    
	public function __construct()
	{
		$this->apiKeyHeader = null;
		$this->apiKeyQuery = null;
		$this->basicAuth = null;
	}
}
